#!/bin/bash
# parallel job using 16 processors. and runs for 4 hours (max)
#SBATCH -N 1 # node count
#SBATCH --ntasks-per-node=4
#SBATCH --ntasks-per-socket=2
#SBATCH --gres=gpu:4
#SBATCH -t 00:20:00
# sends mail when process begins, and
# when it ends. Make sure you define your email
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=dsu@princeton.edu

python train_3.py --model_dir experiments/Net2-5 --teacher cnn2 --layer 5